repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        args: [ --line-length=79, --target-version=py312, --verbose]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]

      - id: isort
        name: Sorting import statements
        entry: bash -c 'isort "$@"; git add -u' --
        language: python
        args: [ "--filter-files", "--check-only"]
        files: \.py$