"""Update test bot

Revision ID: 3f1aaa014298
Revises: c55bfa3449c7
Create Date: 2025-06-27 19:39:50.762192

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3f1aaa014298"
down_revision = "c55bfa3449c7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_bots",
        sa.Column(
            "total_profit",
            sa.Numeric(precision=20, scale=10),
            server_default="0",
            nullable=False,
            comment="Total profit",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_bots", "total_profit")
    # ### end Alembic commands ###
