"""Update models

Revision ID: 282f6961bb89
Revises: 5fe39eb0d7c0
Create Date: 2025-07-01 23:25:54.096028

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "282f6961bb89"
down_revision = "5fe39eb0d7c0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_bots",
        sa.Column(
            "start_updown_ticks",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Start updown ticks",
        ),
    )
    op.add_column(
        "test_orders",
        sa.Column(
            "start_updown_ticks",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Start updown ticks",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_orders", "start_updown_ticks")
    op.drop_column("test_bots", "start_updown_ticks")
    # ### end Alembic commands ###
