"""add column to test_bots

Revision ID: f5143817785b
Revises: 278b868a0ff0
Create Date: 2025-08-04 12:32:21.008513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5143817785b'
down_revision = '278b868a0ff0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_bots', sa.Column('copybot_v2_time_in_minutes', sa.Numeric(), nullable=True, comment='For copy bot version 2 the time it takes for the copy bot v1 being monitored to be profitable'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_bots', 'copybot_v2_time_in_minutes')
    # ### end Alembic commands ###
