"""Added index

Revision ID: e19adb52eb59
Revises: ff34a181d532
Create Date: 2025-07-28 11:56:20.314904

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "e19adb52eb59"
down_revision = "ff34a181d532"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_assethistory_symbol_event_price",
        "asset_history",
        ["symbol", "event_time", "last_price"],
        unique=False,
    )
    op.create_index(
        op.f("ix_asset_history_event_time"),
        "asset_history",
        ["event_time"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_asset_history_event_time"), table_name="asset_history"
    )
    op.drop_index(
        "idx_assethistory_symbol_event_price", table_name="asset_history"
    )
    # ### end Alembic commands ###
