"""Update order table

Revision ID: 1efe667c76e5
Revises: 9d9169de41f2
Create Date: 2025-07-22 19:43:59.471211

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1efe667c76e5"
down_revision = "9d9169de41f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_orders",
        sa.Column(
            "referral_bot_from_profit_func", sa.Integer(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_orders", "referral_bot_from_profit_func")
    # ### end Alembic commands ###
