"""Add time_to_wait_for_entry_price_to_open_order_in_minutes column to test_bots

Revision ID: 95bf45f04825
Revises: 10b776711b23
Create Date: 2025-07-10 08:34:05.312912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95bf45f04825'
down_revision = '10b776711b23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_bots', sa.Column('time_to_wait_for_entry_price_to_open_order_in_minutes', sa.Numeric(precision=10, scale=2), nullable=True, comment='The maximum duration (in minutes) a bot will wait for the entry price to be reached before attempting to open an order'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_bots', 'time_to_wait_for_entry_price_to_open_order_in_minutes')
    # ### end Alembic commands ###
