"""Add copy_bot_max_time_profitability_min column to test_bots

Revision ID: e47320d6e3cb
Revises: 0776684d1f69
Create Date: 2025-07-07 20:11:26.857117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47320d6e3cb'
down_revision = '0776684d1f69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_bots', sa.Column('copy_bot_max_time_profitability_min', sa.Numeric(precision=10, scale=2), nullable=True, comment='For copy bot the maximum time it takes for the original bot being monitored to be profitable'))
    op.add_column('test_bots', sa.Column('copy_bot_min_time_profitability_min', sa.Numeric(precision=10, scale=2), nullable=True, comment='For copy bot the minimum time it takes for the original bot being monitored to be profitable'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_bots', 'copy_bot_min_time_profitability_min')
    op.drop_column('test_bots', 'copy_bot_max_time_profitability_min')
    # ### end Alembic commands ###
