"""Add two columns to test_bots

Revision ID: 4b13091d66c9
Revises: 1efe667c76e5
Create Date: 2025-07-26 20:08:11.820786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b13091d66c9'
down_revision = '1efe667c76e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_bots', sa.Column('consider_ma_for_open_order', sa.Boolean(), nullable=False,
            server_default=sa.false(), comment='Whether to consider the moving average (MA) when opening the order'))
    op.add_column('test_bots', sa.Column('consider_ma_for_close_order', sa.Boolean(), nullable=False,
            server_default=sa.false(), comment='Whether to consider the moving average (MA) when closing the order'))
    op.create_foreign_key(None, 'test_orders', 'test_bots', ['referral_bot_from_profit_func'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_orders', type_='foreignkey')
    op.drop_column('test_bots', 'consider_ma_for_close_order')
    op.drop_column('test_bots', 'consider_ma_for_open_order')
    # ### end Alembic commands ###
