"""Add stop_reason_event column to test_orders

Revision ID: 10b776711b23
Revises: e47320d6e3cb
Create Date: 2025-07-08 18:25:10.902132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b776711b23'
down_revision = 'e47320d6e3cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_orders', sa.Column('stop_reason_event', sa.String(), nullable=True, comment='Reason event of stopping order'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_orders', 'stop_reason_event')
    # ### end Alembic commands ###
