"""Delete field

Revision ID: 9370b3599c6e
Revises: 62d38ba888bd
Create Date: 2025-07-03 21:06:39.158175

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9370b3599c6e"
down_revision = "62d38ba888bd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_bots", "start_ticks")
    op.drop_column("test_orders", "start_ticks")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_orders",
        sa.Column(
            "start_ticks",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
            comment="Start ticks",
        ),
    )
    op.add_column(
        "test_bots",
        sa.Column(
            "start_ticks",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
            comment="Start ticks",
        ),
    )
    # ### end Alembic commands ###
