"""Delete field

Revision ID: c55bfa3449c7
Revises: 4f8bf3b6f9d2
Create Date: 2025-06-24 20:09:00.088546

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c55bfa3449c7"
down_revision = "4f8bf3b6f9d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_bots", "entry_offset_ticks")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_bots",
        sa.Column(
            "entry_offset_ticks",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Entry rejection in ticks (from best_bid/ask)",
        ),
    )
    # ### end Alembic commands ###
