"""Refferal bot

Revision ID: bd886f613cad
Revises: 95bf45f04825
Create Date: 2025-07-16 11:57:11.228747

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bd886f613cad"
down_revision = "95bf45f04825"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_orders",
        sa.Column("referral_bot_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None, "test_orders", "test_bots", ["referral_bot_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "test_orders", type_="foreignkey")
    op.drop_column("test_orders", "referral_bot_id")
    # ### end Alembic commands ###
