"""Update models

Revision ID: 62d38ba888bd
Revises: 282f6961bb89
Create Date: 2025-07-02 20:24:12.755142

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "62d38ba888bd"
down_revision = "282f6961bb89"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_bots", "successful_stop_lose_ticks")
    op.drop_column("test_bots", "stop_ticks")
    op.drop_column("test_orders", "successful_stop_lose_ticks")
    op.drop_column("test_orders", "stop_ticks")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_orders",
        sa.Column(
            "stop_ticks",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
            comment="Stop ticks",
        ),
    )
    op.add_column(
        "test_orders",
        sa.Column(
            "successful_stop_lose_ticks",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
            comment="Stop-loss in ticks after trade "
            "becomes profitable (used to secure partial profit)",
        ),
    )
    op.add_column(
        "test_bots",
        sa.Column(
            "stop_ticks",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
            comment="Stop ticks",
        ),
    )
    op.add_column(
        "test_bots",
        sa.Column(
            "successful_stop_lose_ticks",
            sa.INTEGER(),
            server_default=sa.text("10"),
            autoincrement=False,
            nullable=False,
            comment="Stop-loss in ticks after trade "
            "becomes profitable (used to secure partial profit)",
        ),
    )
    # ### end Alembic commands ###
