"""Add new columns to test_bot

Revision ID: 278b868a0ff0
Revises: e19adb52eb59
Create Date: 2025-08-01 08:50:18.515035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278b868a0ff0'
down_revision = 'e19adb52eb59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_bots', sa.Column('ma_number_of_candles_for_open_order', sa.Numeric(), nullable=True, comment='The number of candles used to calculate the moving average (MA) for the order opening logic'))
    op.add_column('test_bots', sa.Column('ma_number_of_candles_for_close_order', sa.Numeric(), nullable=True, comment='The number of candles used to calculate the moving average (MA) for the order closing logic'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_bots', 'ma_number_of_candles_for_close_order')
    op.drop_column('test_bots', 'ma_number_of_candles_for_open_order')
    # ### end Alembic commands ###
