"""Add min_timeframe_asset_volatility column to test_bots

Revision ID: 0776684d1f69
Revises: 9370b3599c6e
Create Date: 2025-07-07 11:27:50.858537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0776684d1f69'
down_revision = '9370b3599c6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_bots', sa.Column('min_timeframe_asset_volatility', sa.Numeric(precision=10, scale=2), nullable=True, comment='Duration of the time window (in minutes) over which asset volatility is measured'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_bots', 'min_timeframe_asset_volatility')
    # ### end Alembic commands ###
