"""Update order bot model

Revision ID: d363e80f0b4f
Revises: 587cedf6d729
Create Date: 2025-06-30 20:59:44.636048

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d363e80f0b4f"
down_revision = "587cedf6d729"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_orders",
        sa.Column(
            "successful_stop_lose_ticks",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Stop-loss in ticks after trade becomes "
            "profitable (used to secure partial profit)",
        ),
    )
    op.add_column(
        "test_orders",
        sa.Column(
            "start_ticks",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Start ticks",
        ),
    )
    op.add_column(
        "test_orders",
        sa.Column(
            "stop_ticks",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Stop ticks",
        ),
    )
    op.add_column(
        "test_orders",
        sa.Column(
            "take_profit_ticks",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Target Profit/Close in Ticks",
        ),
    )
    op.add_column(
        "test_orders",
        sa.Column(
            "stop_loss_ticks",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Stop ticks",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_orders", "take_profit_ticks")
    op.drop_column("test_orders", "stop_ticks")
    op.drop_column("test_orders", "start_ticks")
    op.drop_column("test_orders", "successful_stop_lose_ticks")
    # ### end Alembic commands ###
