"""AssetOrderBook model

Revision ID: c53bd979947e
Revises: dfc4c6fcf213
Create Date: 2025-06-18 12:54:54.901118

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c53bd979947e"
down_revision = "dfc4c6fcf213"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_order_book",
        sa.Column("asset_exchange_id", sa.Integer(), nullable=False),
        sa.Column(
            "transaction_time",
            sa.Integer(),
            nullable=False,
            comment="Transaction time from Binance (T)",
        ),
        sa.Column(
            "bids",
            sa.JSON(),
            nullable=False,
            comment="List of bid [price, quantity]",
        ),
        sa.Column(
            "asks",
            sa.JSON(),
            nullable=False,
            comment="List of ask [price, quantity]",
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Date and time of create",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Date and time of update",
        ),
        sa.ForeignKeyConstraint(
            ["asset_exchange_id"],
            ["asset_exchange_specs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_asset_order_book_created_at"),
        "asset_order_book",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_asset_order_book_created_at"), table_name="asset_order_book"
    )
    op.drop_table("asset_order_book")
    # ### end Alembic commands ###
