"""Update test bot model

Revision ID: 587cedf6d729
Revises: 29f51f5e6ec5
Create Date: 2025-06-30 19:53:13.336814

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "587cedf6d729"
down_revision = "29f51f5e6ec5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_bots",
        sa.Column(
            "start_ticks",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Start ticks",
        ),
    )
    op.add_column(
        "test_bots",
        sa.Column(
            "stop_ticks",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Stop ticks",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_bots", "stop_ticks")
    op.drop_column("test_bots", "start_ticks")
    # ### end Alembic commands ###
