"""Update model

Revision ID: 5fe39eb0d7c0
Revises: d363e80f0b4f
Create Date: 2025-07-01 19:34:36.213994

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "5fe39eb0d7c0"
down_revision = "d363e80f0b4f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "test_bots", "take_profit_ticks", new_column_name="stop_success_ticks"
    )
    op.alter_column(
        "test_orders",
        "take_profit_ticks",
        new_column_name="stop_success_ticks",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "test_bots", "stop_success_ticks", new_column_name="take_profit_ticks"
    )
    op.alter_column(
        "test_orders",
        "stop_success_ticks",
        new_column_name="take_profit_ticks",
    )
    # ### end Alembic commands ###
