"""Test order model

Revision ID: 5e39af31c315
Revises: d526351d0c0f
Create Date: 2025-06-20 18:31:27.811463

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e39af31c315"
down_revision = "d526351d0c0f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_orders",
        sa.Column(
            "asset_symbol",
            sa.String(),
            nullable=False,
            comment="Trading symbol like BTCUSDT",
        ),
        sa.Column(
            "balance",
            sa.Numeric(),
            nullable=False,
            comment="Starting balance for the order",
        ),
        sa.Column(
            "order_type",
            sa.String(),
            nullable=False,
            comment="Order type: buy/sell",
        ),
        sa.Column(
            "open_price",
            sa.Numeric(),
            nullable=False,
            comment="Opening price of the asset",
        ),
        sa.Column(
            "open_time",
            sa.DateTime(),
            nullable=False,
            comment="Time of order open",
        ),
        sa.Column(
            "open_fee",
            sa.Numeric(),
            nullable=False,
            comment="Fee charged at order open (0.02%)",
        ),
        sa.Column(
            "stop_loss_price",
            sa.Numeric(),
            nullable=False,
            comment="Stop-loss price",
        ),
        sa.Column(
            "close_price", sa.Numeric(), nullable=True, comment="Closing price"
        ),
        sa.Column(
            "close_time",
            sa.DateTime(),
            nullable=True,
            comment="Time of order close",
        ),
        sa.Column(
            "close_fee",
            sa.Numeric(),
            nullable=True,
            comment="Fee charged at order close (0.05%)",
        ),
        sa.Column(
            "profit_loss",
            sa.Numeric(),
            nullable=True,
            comment="Profit or loss after all fees",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether the order is still active",
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Date and time of create",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Date and time of update",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_test_orders_asset_symbol"),
        "test_orders",
        ["asset_symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_test_orders_created_at"),
        "test_orders",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_test_orders_created_at"), table_name="test_orders")
    op.drop_index(
        op.f("ix_test_orders_asset_symbol"), table_name="test_orders"
    )
    op.drop_table("test_orders")
    # ### end Alembic commands ###
