"""Main table

Revision ID: 10fa089f03df
Revises:
Create Date: 2025-06-16 13:07:34.510881

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "10fa089f03df"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_pairs",
        sa.Column(
            "pair",
            sa.String(length=255),
            nullable=False,
            comment="Trading pair, e.g., BTCUSDT",
        ),
        sa.Column(
            "base_asset",
            sa.String(length=255),
            nullable=False,
            comment="Base asset in the trading pair",
        ),
        sa.Column(
            "quote_asset",
            sa.String(length=255),
            nullable=False,
            comment="Quote asset in the trading pair",
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Date and time of create",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Date and time of update",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_asset_pairs_created_at"),
        "asset_pairs",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "exchange_pair_specs",
        sa.Column(
            "source",
            sa.String(length=255),
            server_default="BINANCE",
            nullable=False,
            comment="Source exchange",
        ),
        sa.Column(
            "asset_pairs_id",
            sa.Integer(),
            nullable=True,
            comment="Foreign key to asset_pairs",
        ),
        sa.Column(
            "contract_type",
            sa.String(length=255),
            nullable=False,
            comment="Contract type",
        ),
        sa.Column(
            "symbol", sa.String(length=255), nullable=False, comment="Symbol"
        ),
        sa.Column(
            "delivery_date",
            sa.DateTime(),
            nullable=True,
            comment="Delivery date",
        ),
        sa.Column(
            "onboard_date",
            sa.DateTime(),
            nullable=True,
            comment="Onboard date",
        ),
        sa.Column(
            "status", sa.String(length=50), nullable=True, comment="Status"
        ),
        sa.Column(
            "maint_margin_percent",
            sa.Numeric(),
            nullable=True,
            comment="Maintenance margin percent",
        ),
        sa.Column(
            "required_margin_percent",
            sa.Numeric(),
            nullable=True,
            comment="Required margin percent",
        ),
        sa.Column(
            "base_asset",
            sa.String(length=50),
            nullable=True,
            comment="Base asset",
        ),
        sa.Column(
            "quote_asset",
            sa.String(length=50),
            nullable=True,
            comment="Quote asset",
        ),
        sa.Column(
            "margin_asset",
            sa.String(length=50),
            nullable=True,
            comment="Margin asset",
        ),
        sa.Column(
            "price_precision",
            sa.Integer(),
            nullable=True,
            comment="Price precision",
        ),
        sa.Column(
            "quantity_precision",
            sa.Integer(),
            nullable=True,
            comment="Quantity precision",
        ),
        sa.Column(
            "base_asset_precision",
            sa.Integer(),
            nullable=True,
            comment="Base asset precision",
        ),
        sa.Column(
            "quote_precision",
            sa.Integer(),
            nullable=True,
            comment="Quote precision",
        ),
        sa.Column(
            "underlying_type",
            sa.String(length=50),
            nullable=True,
            comment="Underlying type",
        ),
        sa.Column(
            "underlying_sub_type",
            sa.JSON(),
            nullable=True,
            comment="Underlying sub-type",
        ),
        sa.Column(
            "settle_plan", sa.Integer(), nullable=True, comment="Settle plan"
        ),
        sa.Column(
            "trigger_protect",
            sa.Numeric(),
            nullable=True,
            comment="Trigger protect",
        ),
        sa.Column("filters", sa.JSON(), nullable=True, comment="Filters"),
        sa.Column(
            "order_type", sa.JSON(), nullable=True, comment="Order type"
        ),
        sa.Column(
            "time_in_force", sa.JSON(), nullable=True, comment="Time in force"
        ),
        sa.Column(
            "liquidation_fee",
            sa.Numeric(),
            nullable=True,
            comment="Liquidation fee",
        ),
        sa.Column(
            "market_take_bound",
            sa.Numeric(),
            nullable=True,
            comment="Market take bound",
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Date and time of create",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Date and time of update",
        ),
        sa.ForeignKeyConstraint(
            ["asset_pairs_id"], ["asset_pairs.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exchange_pair_specs_asset_pairs_id"),
        "exchange_pair_specs",
        ["asset_pairs_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exchange_pair_specs_created_at"),
        "exchange_pair_specs",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "assets_history",
        sa.Column("id", sa.Integer(), nullable=False, comment="Primary key"),
        sa.Column(
            "exchange_pair_id",
            sa.Integer(),
            nullable=True,
            comment="Foreign key to exchange_pair_specs",
        ),
        sa.Column(
            "symbol",
            sa.String(length=255),
            nullable=False,
            comment="Symbol (s)",
        ),
        sa.Column(
            "source",
            sa.String(length=255),
            server_default="BINANCE",
            nullable=False,
            comment="Source exchange",
        ),
        sa.Column(
            "last_price", sa.Numeric(), nullable=True, comment="Last price (c)"
        ),
        sa.Column(
            "price_change_24h",
            sa.Numeric(),
            nullable=True,
            comment="Price change in 24h (p)",
        ),
        sa.Column(
            "price_change_percent_24h",
            sa.Numeric(),
            nullable=True,
            comment="Price change percent in 24h (P)",
        ),
        sa.Column(
            "base_asset_volume_24h",
            sa.Numeric(),
            nullable=True,
            comment="Base asset volume in 24h (v)",
        ),
        sa.Column(
            "quote_asset_volume_24h",
            sa.Numeric(),
            nullable=True,
            comment="Quote asset volume in 24h (q)",
        ),
        sa.Column(
            "weighted_avg_price_24h",
            sa.Numeric(),
            nullable=True,
            comment="Weighted average price in 24h (w)",
        ),
        sa.Column(
            "high_24h",
            sa.Numeric(),
            nullable=True,
            comment="24h high price (h)",
        ),
        sa.Column(
            "low_24h", sa.Numeric(), nullable=True, comment="24h low price (l)"
        ),
        sa.Column(
            "event_time",
            sa.DateTime(),
            nullable=False,
            comment="Event time (E)",
        ),
        sa.Column(
            "statistics_open_time",
            sa.BigInteger(),
            nullable=True,
            comment="Statistics open time (O)",
        ),
        sa.Column(
            "statistics_close_time",
            sa.BigInteger(),
            nullable=True,
            comment="Statistics close time (C)",
        ),
        sa.ForeignKeyConstraint(
            ["exchange_pair_id"],
            ["exchange_pair_specs.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assets_history_exchange_pair_id"),
        "assets_history",
        ["exchange_pair_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assets_history_id"), "assets_history", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assets_history_id"), table_name="assets_history")
    op.drop_index(
        op.f("ix_assets_history_exchange_pair_id"), table_name="assets_history"
    )
    op.drop_table("assets_history")
    op.drop_index(
        op.f("ix_exchange_pair_specs_created_at"),
        table_name="exchange_pair_specs",
    )
    op.drop_index(
        op.f("ix_exchange_pair_specs_asset_pairs_id"),
        table_name="exchange_pair_specs",
    )
    op.drop_table("exchange_pair_specs")
    op.drop_index(op.f("ix_asset_pairs_created_at"), table_name="asset_pairs")
    op.drop_table("asset_pairs")
    # ### end Alembic commands ###
