"""Update field

Revision ID: 07113a535263
Revises: c53bd979947e
Create Date: 2025-06-18 13:26:14.300107

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "07113a535263"
down_revision = "c53bd979947e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "asset_order_book",
        "transaction_time",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="Transaction time from Binance (T)",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "asset_order_book",
        "transaction_time",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="Transaction time from Binance (T)",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
