"""WatchedPair

Revision ID: 5d5fc60bcb99
Revises: abff0bc26037
Create Date: 2025-06-16 14:50:16.986338

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5d5fc60bcb99"
down_revision = "abff0bc26037"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "watched_pair",
        sa.Column(
            "exchange_pair_id",
            sa.Integer(),
            nullable=True,
            comment="Foreign key to exchange_pair_specs",
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Date and time of create",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Date and time of update",
        ),
        sa.ForeignKeyConstraint(
            ["exchange_pair_id"],
            ["exchange_pair_specs.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_watched_pair_created_at"),
        "watched_pair",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_watched_pair_exchange_pair_id"),
        "watched_pair",
        ["exchange_pair_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_watched_pair_exchange_pair_id"), table_name="watched_pair"
    )
    op.drop_index(
        op.f("ix_watched_pair_created_at"), table_name="watched_pair"
    )
    op.drop_table("watched_pair")
    # ### end Alembic commands ###
